version: "3.8"

services:
  easypanel:
    image: easypanel/easypanel:latest
    container_name: easypanel
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      PANEL_USER: admin
      PANEL_PASSWORD: GrpOln20//tec
    volumes:
      - ./easypanel_data:/data

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: usuario
      N8N_BASIC_AUTH_PASSWORD: tu_password
      WEBHOOK_URL: "${WEBHOOK_URL}"
      N8N_EDITOR_BASE_URL: "${WEBHOOK_URL}"
      N8N_DEFAULT_BINARY_DATA_MODE: filesystem
    volumes:
      - ./n8n_data:/home/node/.n8n
