version: "3.8"

services:
  # EasyPanel
  easypanel:
    image: easypanel/easypanel:latest
    container_name: easypanel
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      PANEL_USER: "${PANEL_USER}"
      PANEL_PASSWORD: "${PANEL_PASSWORD}"
    volumes:
      - ./easypanel_data:/data

  # n8n
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      N8N_BASIC_AUTH_ACTIVE: "${N8N_BASIC_AUTH_ACTIVE}"
      N8N_BASIC_AUTH_USER: "${N8N_BASIC_AUTH_USER}"
      N8N_BASIC_AUTH_PASSWORD: "${N8N_BASIC_AUTH_PASSWORD}"
      WEBHOOK_URL: "${WEBHOOK_URL}"
      N8N_EDITOR_BASE_URL: "${N8N_EDITOR_BASE_URL}"
      N8N_DEFAULT_BINARY_DATA_MODE: filesystem
    volumes:
      - ./n8n_data:/home/node/.n8n
